name: Build and Deploy

on:
  push:
    branches:
      - main # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: yarn install

      - name: Build Next.js project
        run: yarn build

      - name: Upload static site as artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-artifact
          path: out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs-artifact
          path: out

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out # The folder containing your static files
          publish_branch: gh-pages # Deploy to the gh-pages branch
          keep_files: true
